name: srsRAN 4G Derleme Testi

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Kodu Çek
        uses: actions/checkout@v4
        
     - name: Bağımlılıkları Yükle
        run: |
          sudo apt update
          sudo apt install -y cmake make gcc g++ \
            libfftw3-dev libmbedtls-dev libsctp-dev \
            libzmq3-dev libczmq-dev libconfig++-dev \
            libyaml-cpp-dev libgtest-dev \
            libunwind-dev libdw-dev # Hata ayıklama için statik destekleri

      - name: Derleme Klasörünü Oluştur
        run: mkdir build

      - name: CMake Yapılandırması (Statik)
        working-directory: ./build
        run: |
          cmake ../ -DENABLE_ZEROMQ=ON \
                    -DENABLE_STATIC=ON \
                    -DENABLE_WERROR=OFF \
                    -DCMAKE_BUILD_TYPE=Release

      - name: Derlemeyi Başlat (Make)
        working-directory: ./build
        run: make -j$(nproc)

      - name: Dosyaları Paketle ve Yükle (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: srsRAN-Project-Binaries
          path: |
            build/apps/gnb/gnb
            build/apps/ue/ue
          if-no-files-found: error # Dosya bulunamazsa hata ver ki nerede olduğunu görelim
