name: srsRAN 4G Derleme Testi

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Kodu Çek
      uses: actions/checkout@v3

  - name: Bağımlılıkları Yükle
      run: |
        sudo apt update
        sudo apt install -y cmake make gcc g++ \
          libfftw3-dev libmbedtls-dev libsctp-dev \
          libzmq3-dev libczmq-dev libconfig++-dev \
          libyaml-cpp-dev libgtest-dev # <--- yaml-cpp buraya eklendi

    - name: Derleme Klasörünü Oluştur
      run: mkdir build

    - name: CMake Yapılandırması
      working-directory: ./build
      run: cmake ../ -DENABLE_ZEROMQ=ON

    - name: Derlemeyi Başlat (Make)
      working-directory: ./build
      run: make -j$(nproc)

    - name: Başarı Kontrolü
      run: echo "Derleme başarıyla tamamlandı!"
      
